apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-z1
  namespace: learn07
  labels:
    app: busybox-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
      - name: busybox
        image: busybox:1.36.1
        imagePullPolicy: IfNotPresent
        command: ['/bin/sh']
        args:
          - -c
          - >-
            while true; do sleep 5; echo "$(date)" >> /output/test.log; done;
        volumeMounts:
          - name: data
            mountPath: /output
      - name: multitool
        image: wbitt/network-multitool
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: data
            mountPath: /input
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-data