apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: learn07
spec:
  storageClassName: "microk8s-hostpath"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi